### ISSUE TITLE
[bug] Execution Error on all platforms

### ISSUE THREAD

**Issue by gibbiemonster** [BlockArchitech/MusicBridge#16]
~~Due to a bug in macOS Ventura, System `osascript` does not work properly causing -600 execution errors. Unfortunately, there is nothing I can do here until a patch is issued.~~

A bug in system events is causing musicbridge to behave improperly. A workaround will have to be found in the time being.

**Comment by blockarchitech** [comment]
Apple refuses to acknowledge this issue. Scheduled a meeting with apple to explain said issue

**Comment by gibbiemonster** [comment]
New error!

I am now seeing -10000, which means the event handler did not run properly. This now affects all platforms.

**Comment by gibbiemonster** [comment]
Known affected macOS versions:
macOS Big Sur 11.6+
macOS Ventura 13.x
macOS Monterey 12.1? Uncertain

**Comment by gibbiemonster** [comment]
Apple removed the entitlement associated with apple events and sending to external apps. This is now fixed in the upcoming version.
