### ISSUE TITLE
The entire app is borked.

### ISSUE THREAD

**Issue by gibbiemonster** [BlockArchitech/MusicBridge#5]
Well, new exciting news.

Console is reporting a stupid number of errors and faults, and CoreMIDI keeps crashing as a result. Tracking here

**Comment by BlockArchitech** [comment]
I'll try to give development logs, and code I think is the issue tomorrow. I'm super tired right now and there's zero way I'm doing any of this tonight 😅

**Comment by gibbiemonster** [comment]
9fbd0fa fixed this. CoreMIDI in Swift is horrible.
